### ISSUE TITLE
Cargar partida

### ISSUE THREAD

**Issue by mortizfe11** [EnginyeriaSofwareUB/ES2017B2#22]
Cargar los personajes escogidos en la partida y en la posición y/o situación correcta (dispersos en el mapa).

Estimación: 6h

**Comment by llam05** [comment]
La comunicación entre escenas falla. Queda pendiente para el sprint 3 por falta de tiempo

**Comment by llam05** [comment]
Los personajes elegidos se muestran correctamente en la escena de partida. Para conseguirlo, se ha implementado una clase Singleton para la persistencia de datos. 

Tiempo: 4 H
