### ISSUE TITLE
Gestión de los mecanismos de movimiento y salud by adri

### ISSUE THREAD

**Issue by llam05** [EnginyeriaSofwareUB/ES2017B2#36]
Asignar a cada personaje la barra de vida, energí y se encarga de eliminar el personaje del juego.

**Comment by adry0094** [comment]
Tiempo estimado: 8h

**Comment by adry0094** [comment]
Llevo unas 2 horas y poco, en principio, como aún no hay daño con la bala solo quedaria que no gire la barra con el muñeco

**Comment by adry0094** [comment]
1 h más para ajustar, pero sigue sin funcionar el fijar la barra de salud
