### ISSUE TITLE
Resultado final

### ISSUE THREAD

**Issue by llam05** [EnginyeriaSofwareUB/ES2017B2#38]
Crear escena con el resultado final por equipos

**Comment by llam05** [comment]
Estimado: 6H

**Comment by DavidMx2** [comment]
Al morir un jugador cualquiera, se muestra la pantalla de final de partida, con dos opciones reiniciar o menu princilal.

En el futuro, falta determinar que jugador ha ganado y poner la condición de victoria en el juego.
