### ISSUE TITLE
Arreglo del árbol

### ISSUE THREAD

**Issue by adry0094** [EnginyeriaSofwareUB/ES2017B2#65]
El árbol no se destruye, entonces una opción es poner el prefab de debajo del árbol indestructible (otro tag p.e.)

**Comment by DavidMx2** [comment]
Si le ponemos al arbol el mismo tag que el terreno, se destruira como este

**Comment by adry0094** [comment]
Creo que forma parte del fondo de pantalla

**Comment by adry0094** [comment]
Al final se queda como está
