### ISSUE TITLE
Muerte del jugador y volver a pantalla inicial

### ISSUE THREAD

**Issue by adry0094** [EnginyeriaSofwareUB/ES2017B2#9]
Implementación de la muerte del jugador al caer del terreno.

Tiempo estimado: 3 Horas

**Comment by llam05** [comment]
primera implementación: Al detectar colisión el jugador volvía la aposición inicial.

**Comment by llam05** [comment]
Implementada retorno al menú de inicio al caer al agua.

Tiempo de tarea: 3h
